name: 'Get & Cache Dependencies'
description: 'get the dependencies and cache them'
runs:
  using: 'composite'
  steps:
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v3
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
    -name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true' || steps.cache-deps.outputs.cache-hit == 'false'
      # This will run if the cache was not hit
      # and will install the dependencies from the package.json file
      run: npm ci
      shell: bash
      # This will run if the cache was hit
      # and will install the dependencies from the cache

