name: First Workflow
on: 
  schedule:
    - cron: '15 9 * * *'
    - cron: '25 16 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs: 
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Output event data
        run: echo "${{ toJson(github.event) }}"

      # - name: Run linting
      #   run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Deploy Code
        run: echo "Deploying code..."
