name: First Workflow
on: workflow_dispatch
jobs: 
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Deploy Code
        run: echo "Deploying code..."
