name: First Workflow
on: workflow_dispatch
jobs: 
  firstjob:
    runs-on: mac0s-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "goodbye"
