name: First Workflow
on: 
  schedule:
    - cron: '15 9 * * *'
    - cron: '25 16 * * *'
  push:
    # branches:
    #   - main
    #trying again but without skip ci as a base test
    # paths:
    #   - '.github/workflows/main copy.yml'
    # paths-ignore:
    #   - '.github/workflows/main.yml'
    # you may only define one of `paths` and `paths-ignore` for a single event
jobs: 
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
#cache saves time by reusing dependencies
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps


      - name: Output event data
        run: echo "${{ toJson(github.event) }}"
        # This will output the entire event data to the console
        # You can also use `echo "${{ github.event_name }}"` to get the event name

      # - name: Run linting
      #   run: npm run lint

      - name: Run tests
        id: 'run-tests'
        run: npm run test

      - name: Run tests report
        if: ${{ steps.run-tests.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results

      - name: Deploy Code
        run: echo "Deploying code..."
        #just testing the skip ci test with push as was unsuccessful with dispatch.