name: First Workflow
on: workflow_dispatch
jobs: 
# env:
#   username: ${{ secrets.GITHUB_USERNAME }}
#   password: ${{ secrets.GITHUB_TOKEN }}
#   repo: ${{ github.repository }}
#   branch: ${{ github.ref_name }}
#   commit: ${{ github.sha }}
# env allows you to set environment variables for all jobs in the workflow
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        

      - name: Run tests
        run: npm run test

      - name: Deploy Code
        run: echo "Deploying code..."
#testing out how to skip ci with git commit
#ci skip works in the commit message
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results

